

sudo: false
language: android #Applicable to an android App
jdk: oraclejdk8

android:
  components:
    # Update Android SDK Tools
    - tools
    - tools

    - build-tools-28.0.3
    - android-28

    # Support library
    - extra-android-support
    - extra-android-m2repository

before_install:
  - yes | sdkmanager "platforms;android-28"


before_script:
  - chmod +x gradlew


script:
  - ./gradlew assemble

licenses:
  - '.+'
