

sudo: false
language: android #Applicable to an android App
jdk: oraclejdk8

android:
  components:
    # Update Android SDK Tools
    - tools
    - tools

    - build-tools-23.0.1
    - android-23

    # Support library
    - extra-android-support
    - extra-android-m2repository

before_install:
  - yes | sdkmanager "platforms;android-23"
script:
  - ./gradlew assemble

licenses:
  - '.+'
